[build]
  command = "npx eleventy"
  publish = "dist"

[dev]
  command = "npx eleventy --watch"
  publish = "dist"


[[redirects]]
  from = "/api/hello"
  to = "/.netlify/functions/hello"
  response = 200


[[edge_functions]]
  path = "/"
  function = "feature-checks"


