[build]
  command = "npx eleventy"
  publish = "dist"

[dev]
  command = "npx eleventy --watch"
  publish = "dist"


# [[redirects]]
#   from = "/api/hello"
#   to = "/.netlify/functions/hello"
#   status = 200


[[edge_functions]]
  path = "/"
  function = "feature-checks"


